// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjpSIyFMd2QmTnaY6NqXFEzTzmzJhY93I',
    appId: '1:973739607499:web:302575d73f299ece03224e',
    messagingSenderId: '973739607499',
    projectId: 'atomid-erp',
    authDomain: 'atomid-erp.firebaseapp.com',
    storageBucket: 'atomid-erp.firebasestorage.app',
    measurementId: 'G-TG7ETT3T47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbPHQC_x_lrm2v47RxKyv9zcqTvG2RNCE',
    appId: '1:973739607499:android:99eded40099858cc03224e',
    messagingSenderId: '973739607499',
    projectId: 'atomid-erp',
    storageBucket: 'atomid-erp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjpSIyFMd2QmTnaY6NqXFEzTzmzJhY93I',
    appId: '1:973739607499:web:434fcecdb64c597103224e',
    messagingSenderId: '973739607499',
    projectId: 'atomid-erp',
    authDomain: 'atomid-erp.firebaseapp.com',
    storageBucket: 'atomid-erp.firebasestorage.app',
    measurementId: 'G-TXFH3FFNNP',
  );
}
