// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:atomid/data/models/action_history_model.dart';
import 'package:atomid/data/models/company_model.dart';
import 'package:atomid/data/models/customer_ledger_model.dart';
import 'package:atomid/data/models/customer_model.dart';
import 'package:atomid/data/models/expense_model.dart';
import 'package:atomid/data/models/inventory_movement_model.dart';
import 'package:atomid/data/models/invoice_settings_model.dart';
import 'package:atomid/data/models/loyalty_settings_model.dart';
import 'package:atomid/data/models/loyalty_transaction_model.dart';
import 'package:atomid/data/models/product_model.dart';
import 'package:atomid/data/models/purchase_model.dart';
import 'package:atomid/data/models/sale_model.dart';
import 'package:atomid/data/models/settings_model.dart';
import 'package:atomid/data/models/supplier_ledger_model.dart';
import 'package:atomid/data/models/supplier_model.dart';
import 'package:atomid/data/models/sync_log_model.dart';
import 'package:atomid/data/models/sync_queue_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ActionHistoryAdapter());
    registerAdapter(CompanyModelAdapter());
    registerAdapter(CustomerAdapter());
    registerAdapter(CustomerLedgerAdapter());
    registerAdapter(ExpenseAdapter());
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(InventoryMovementAdapter());
    registerAdapter(InvoiceSettingsModelAdapter());
    registerAdapter(LoyaltySettingsModelAdapter());
    registerAdapter(LoyaltyTransactionAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductVariantAdapter());
    registerAdapter(PurchaseAdapter());
    registerAdapter(PurchaseItemAdapter());
    registerAdapter(SaleAdapter());
    registerAdapter(SaleItemAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SupplierAdapter());
    registerAdapter(SupplierLedgerAdapter());
    registerAdapter(SyncLogModelAdapter());
    registerAdapter(SyncQueueItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ActionHistoryAdapter());
    registerAdapter(CompanyModelAdapter());
    registerAdapter(CustomerAdapter());
    registerAdapter(CustomerLedgerAdapter());
    registerAdapter(ExpenseAdapter());
    registerAdapter(ExpenseCategoryAdapter());
    registerAdapter(InventoryMovementAdapter());
    registerAdapter(InvoiceSettingsModelAdapter());
    registerAdapter(LoyaltySettingsModelAdapter());
    registerAdapter(LoyaltyTransactionAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductVariantAdapter());
    registerAdapter(PurchaseAdapter());
    registerAdapter(PurchaseItemAdapter());
    registerAdapter(SaleAdapter());
    registerAdapter(SaleItemAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(SupplierAdapter());
    registerAdapter(SupplierLedgerAdapter());
    registerAdapter(SyncLogModelAdapter());
    registerAdapter(SyncQueueItemAdapter());
  }
}
